name: Recompile

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  recompile:
    runs-on: ubuntu-latest

    steps:
      - name: Define environment variables
        run: |
          # Build-Tools 34 corrupts APKs when apksigner signs them, fixed in 35
          # Available versions: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#android
          echo "ANDROID_BUILD_TOOLS=$ANDROID_HOME/build-tools/36.0.0" >> $GITHUB_ENV

      - name: Clone
        uses: actions/checkout@v4

      - name: Download apktool
        run: wget --no-verbose -O apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.11.0/apktool_2.11.0.jar

      - name: Decompile app
        run: java -jar apktool.jar decode *.apk -o decompiled

      - name: Modify source
        run: dotnet fsi tweak.fsx

      - name: Compile app
        run: java -jar apktool.jar build decompiled -o Wunderground-faststart-unsigned.apk

      - name: Sign APK
        env: 
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > cert.keystore
          $ANDROID_BUILD_TOOLS/apksigner sign --ks cert.keystore --ks-pass env:KEYSTORE_PASSWORD --align-file-size --in Wunderground-faststart-unsigned.apk --out Wunderground-faststart.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Wunderground-faststart.apk
          path: Wunderground-faststart.apk
          if-no-files-found: error